
//----------------------------------------------------
// The following code was generated by CUP v0.11a beta 20060608
// Mon Mar 02 11:46:57 COT 2020
//----------------------------------------------------

package main;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int Double = 8;
  public static final int If = 10;
  public static final int Operador_booleano = 27;
  public static final int Parentesis_cerrado = 29;
  public static final int Byte = 3;
  public static final int Operador_atribucion = 25;
  public static final int Dos_Puntos = 20;
  public static final int Else = 11;
  public static final int Llave_abierta = 30;
  public static final int Long = 6;
  public static final int Punto = 22;
  public static final int While = 13;
  public static final int Division = 19;
  public static final int Int = 4;
  public static final int Cadena = 9;
  public static final int Float = 7;
  public static final int Corchete_cerrado = 33;
  public static final int Operador_incremento = 26;
  public static final int For = 14;
  public static final int EOF = 0;
  public static final int error = 1;
  public static final int Operador_relacional = 24;
  public static final int Parentesis_abierto = 28;
  public static final int Char = 5;
  public static final int ERROR = 37;
  public static final int Do = 12;
  public static final int Punto_Coma = 21;
  public static final int Identificador = 35;
  public static final int Operador_logico = 23;
  public static final int Resta = 17;
  public static final int Corchete_abierto = 32;
  public static final int Llave_cerrada = 31;
  public static final int Multiplicacion = 18;
  public static final int Numero = 36;
  public static final int Suma = 16;
  public static final int Main = 34;
  public static final int Igual = 15;
  public static final int Comillas = 2;
}

