package main;
/**
 *
 * @author daniel
 */
public enum Tokens {
    Comillas,
    Byte,
    Int,
    Char,
    Long,
    Float,
    Double,
    Cadena,
    If,
    Else,
    Do,
    While,
    For,
    Igual,
    Suma,
    Resta,
    Multiplicacion,
    Division,
    Dos_Puntos,
    Punto_Coma,
    Punto,
    Operador_logico,
    Operador_relacional,
    Operador_atribucion,
    Operador_incremento,
    Operador_booleano,
    Parentesis_abierto,
    Parentesis_cerrado,
    Llave_abierta,
    Llave_cerrada,
    Corchete_abierto,
    Corchete_cerrado,
    Main,
    Identificador,
    Numero,
    ERROR
}